### ISSUE TITLE
Prometheus scraping in helm deployment not working

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/parseable#1032]
`/about` output:

```json
{
  "version": "v1.6.3",
  "commit": "28b984a",
}
```

Description:
The default setting:
```
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/api/v1/metrics"
```
in the values.yaml will not work (anymore) - prometheus is unable to scrape this endpoint because it is protected (`You don't have permission to access this resource. Please contact your administrator for assistance.`) and prometheus receives a `401` when scraping it
