### ISSUE TITLE
`BasicAuth` extract error: invalid Header provided for correctly configured headers

### ISSUE THREAD

**Issue by sikula** [parseablehq/parseable#1214]
`/about` output:

```json
{
  "version": "v1.7.3",
  "uiVersion": "v0.9.18",
  "commit": "624aef0",
  "deploymentId": "01JN3J24J4D87B8TKMV4R75484",
  "updateAvailable": false,
  "latestVersion": "v1.7.3",
  "llmActive": false,
  "llmProvider": null,
  "oidcActive": false,
  "license": "AGPL-3.0-only",
  "mode": "Standalone",
  "staging": "/staging",
  "hotTier": "Disabled",
  "grpcPort": 8001,
  "store": {
    "type": "S3 bucket",
    "path": "http://minio:9000/newrali-local"
  },
  "analytics": {
    "clarityTag": null
  }
}
```

Description:

When forwarding logs from otel collector, Parseable logs failed with `DEBUG actix_web_httpauth::extractors::basic: `BasicAuth` extract error: invalid Header provided` even though the otel collector is correctly configured with the correct Authorization header, confirmed because a curl request with the exact same header successfully creates an event in Parseable

**Comment by nitisht** [comment]
Thanks for reporting @sikula we'll take a look shortly

**Comment by sainad2222** [comment]
I think the error `BasicAuth extract error: invalid Header provided`  is expected behavior in general UI flow and not a ingestion bug.
The debug message is normal operation of Parseable's auth system.

**Root Cause**
Parseable's authentication middleware `actix.rs:51-53` attempts BasicAuth extraction first, then falls back to session cookies when BasicAuth fails. When the UI makes authenticated requests after login, it uses session cookies rather than Authorization headers. The `actix_web_httpauth` crate logs this debug message when it can't parse a BasicAuth header (because none exists), but the authentication system correctly falls back to session-based auth. So this is not related to ingestion

I tried to reproduce and ingestion working as expected. Here are the steps
1. Start parseable
`P_USERNAME=parseadmin P_PASSWORD=parseadmin RUST_LOG=debug cargo run local-store`
2. Put this otel config in `config.yaml` and start otelcol by running `otelcol --config config.yaml`
```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"


exporters:
  otlphttp/parseabletraces:
    endpoint: "http://localhost:8000"
    headers:
      Authorization: Basic cGFyc2VhZG1pbjpwYXJzZWFkbWlu
      X-P-Log-Source: otel-traces
      X-P-Stream: otel-traces
      Content-Type: application/json
    encoding: json
    tls:
      insecure: true

  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/parseabletraces, debug]
```
3. Ingest sample trace to otel endpoint
```
curl -X POST http://localhost:4318/v1/traces -H "Content-Type: application/json" -d '{  
    "resourceSpans": [{
      "resource": {
        "attributes": [
          {"key": "service.name", "value": {"stringValue": "test-service"}},
          {"key": "service.version", "value": {"stringValue": "1.0.0"}}
        ]
      },
      "scopeSpans": [{
        "spans": [{
          "traceId": "12345678901234567890123456789012",
          "spanId": "1234567890123456",
          "name": "test-operation",
          "kind": 1,
          "startTimeUnixNano": "1640995200000000000",
          "endTimeUnixNano": "1640995201000000000",
          "attributes": [
            {"key": "http.method", "value": {"stringValue": "GET"}},
            {"key": "http.url", "value": {"stringValue": "http://example.com/api"}}
          ]
        }]
      }]
    }]
  }'
```
Logs at otel
```
2025-08-07T16:02:37.676+0530    info    Traces  {"resource": {"service.instance.id": "9c23cfe4-c93d-4ae9-962d-2140bdf87d45", "service.name": "otelcol", "service.version": "0.131.0"}, "otelcol.component.id": "debug", "otelcol.component.kind": "exporter", "otelcol.signal": "traces", "resource spans": 1, "spans": 1}
2025-08-07T16:02:37.678+0530    info    ResourceSpans #0
Resource SchemaURL:
Resource attributes:
     -> service.name: Str(test-service)
     -> service.version: Str(1.0.0)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope
Span #0
    Trace ID       : 12345678901234567890123456789012
    Parent ID      :
    ID             : 1234567890123456
    Name           : test-operation
    Kind           : Internal
    Start time     : 2022-01-01 00:00:00 +0000 UTC
    End time       : 2022-01-01 00:00:01 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> http.method: Str(GET)
     -> http.url: Str(http://example.com/api)
        {"resource": {"service.instance.id": "9c23cfe4-c93d-4ae9-962d-2140bdf87d45", "service.name": "otelcol", "service.version": "0.131.0"}, "otelcol.component.id": "debug", "otelcol.component.kind": "exporter", "otelcol.signal": "traces"}
```
Logs at parseable
```
2025-08-07T10:33:17.57152Z  INFO actix-rt|system:0|arbiter:1 ThreadId(44) actix_web::middleware::logger:424: 127.0.0.1 "POST /v1/traces HTTP/1.1" 200 0 "-" "OpenTelemetry Collector/0.131.0 (darwin/arm64)" 0.002359
```

<img width="863" height="644" alt="Image" src="https://github.com/user-attachments/assets/3a6c719e-d548-44d8-bfac-819bc4a2a1d4" />
