### ISSUE TITLE
Feature Request: Access AWS S3 via IRSA

### ISSUE THREAD

**Issue by putnam120** [parseablehq/parseable#393]
From the documentation it appears that in order to access AWS S3 from a Kubernetes cluster you need to provide access and secret keys. However, when working with an EKS cluster, or any cluster that has enabled AWS IAM Roles as Service Accounts (IRSA) it would be better to use the service account instead of having to provide credentials.

**Comment by nitisht** [comment]
Hey @putnam120 thanks for reporting, we recently added support for this. You can now set an env var with the AWS profile name so Parseable can authenticate with S3 using that profile: https://www.parseable.io/docs/env-vars#applicable-to-aws

We'll improve docs further so this is more clear. But just to make sure, this is what you are looking for, right?

**Comment by nitisht** [comment]
Thanks @putnam120, I believe this should be possible, but we need to try and document this in detail. Let me get back on this.

**Comment by putnam120** [comment]
@nitisht Yeah I can definitely give it  try and let you know how things go. I should have some time over the weekend to take a look.

**Comment by nitisht** [comment]
Thanks, i’ll get back

**Comment by putnam120** [comment]
Hi @nitisht,

I attempted to deploy to an EKS cluster and use the changes you made for IRSA but hit an issue.
The pod for the deployment hit a CrashLoopBackOff, and its logs said
```
error: the following required arguments were not provided:
  --access-key-id <access-key>
  --secret-key <secret-key>
```

Here are the steps that I took for the deployment:
* checkout the main branch of the git repo and build the image.
* Push the image to my container repository.
* Created the `parseable-env-secret` using the file contents described below.
* Created a `values.yaml` file as described below.
* Obtained all the k8s yaml configurations by running `helm template parseable parseable/parseable -n parseable -f values.yaml  > resources.yaml`.
* Updated the image used by the deployment to the one that I previously pushed to my container repository.
* Used `kubectl` to apply the secret and then the `resources.yaml` file.

`parseable-env-secret` file
```
s3.url=https://s3.amazonaws.com
s3.region=us-east-1
s3.bucket=my-bucket
addr=0.0.0.0:8000
staging.dir=./staging
fs.dir=./data
username=admin
password=admin
```

`values.yaml` file
```
parseable:
  metrics:
    serviceMonitor:
      enabled: false

  s3ModeSecret:
    - type: env
      name: parseable-env-secret
      prefix: P_
      keys:
          - addr
          - username
          - password
          - staging.dir
          - fs.dir
          - s3.url
          - s3.bucket
          - s3.region
```
IN this file I removed the keys for the access and secret keys as they should not be needed once using IRSA. Let me know if I'm mistaken on that point. But if they are used then from my understanding of the AWS SDK will first use the environment variables and later the web identity token (https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) so putting dummy values here isn't possible.
