### ISSUE TITLE
Version 1.0.0 does not start but version 0.9.0 does

### ISSUE THREAD

**Issue by thinkORo** [parseablehq/parseable#785]
I tried the new version 1.0.0 but it doesn't start any longer. I have a docker-compose file for 0.9.0 and that works as expected.

My docker-compose.yml is like this:

```
# version: "3"
volumes:
  redpanda: null
networks:
  parseable: null
services:
  parseable:
    image: containers.parseable.com/parseable/parseable:latest
    command:
      - parseable
      - s3-store
    restart: no # unless-stopped
    ports:
      - 8000:8000
    volumes:
      - /parseable/staging:/staging
    env_file:
      - ./parseable.env
```

Switching from `image: containers.parseable.com/parseable/parseable:latest` back to `parseable/parseable:v0.9.0` and everything works as expected.

What can I observe? Well nothing as there is no log from the container start and there is no service bound to port 8000.
