### ISSUE TITLE
make storageclass in ingestor configurable for helm chart

### ISSUE THREAD

**Issue by daniel-duchon** [parseablehq/parseable#860]
Currently,

the storageclass for ingestor is currently hardcoded to `do-block-storage`:
https://github.com/parseablehq/parseable/blob/main/helm/templates/ingestor-statefulset.yaml#L69-L77
```
[...]
  volumeClaimTemplates:
  - metadata:
      name: stage-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 10Gi
```

This should be changed, so you can also use the ingestor on other cloudproviders than digitalocean.

possible solution would be to use the same code as for the data or stage pvc:
https://github.com/parseablehq/parseable/blob/main/helm/templates/data-pvc.yaml
