### ISSUE TITLE
Multiple serviceMonitor issues

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/parseable#905]
### Additional labels not working
When adding `additionalLabels` in the metrics section of the values.yaml file, e.g.

```
  metrics:
    serviceMonitor:
      enabled: ${service_monitor_enabled}
      namespace: ${namespace}
      interval: 30s
      scrapeTimeout: ""
      relabellings: []
      metricRelabelings: []
      honorLabels: false
      additionalLabels:
        release: grafana
      podTargetLabels: []
```

The following error occurs:

```
Error: template: parseable/templates/service-monitor.yaml:9:8: executing "parseable/templates/service-monitor.yaml" at <include>: wrong number of args for include: want 2 got 1
```

### Custom port does not exist
The serviceMonitor wants to bind the `endpoint port` as `parseable-metrics`. This custom named port does not exist and should be replaced with the existing `parseable-port`.

### Endpoint path not defined
The serviceMonitor does not define an endpoint path. It should point to `/api/v1/metrics`

### Matched labels do not exist
The serviceMonitor has the following selector:
```
selector:
    matchLabels:
      app.kubernetes.io/instance: parseable
      app.kubernetes.io/name: parseable
```
but these labels do not exist on the parseable service object(s). The only label on the services is `app.kubernetes.io/managed-by=Helm`
